"""
Report Generator — PDF OSINT Dossier for any ticker.
Combines all signals, risk scores, supply chain data into a readable report.
Uses weasyprint or reportlab for PDF generation.
"""
import logging
import os
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)


class ReportGenerator:
    async def generate_dossier(self, ticker: str) -> dict:
        ticker = ticker.upper()
        result = {
            "ticker": ticker,
            "report_title": f"OSINT Dossier: {ticker}",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "sections": [],
            "file_path": None,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        sections = []

        sections.append({
            "title": "Executive Summary",
            "content": f"OSINT analysis report for {ticker}. "
                       f"Generated by MarketPulse Intelligence Platform.",
            "type": "summary",
        })

        try:
            from app.services.intelligence.alpha_aggregator import alpha_aggregator
            alpha = await alpha_aggregator.get_alpha_score(ticker)
            sections.append({
                "title": "Alpha Score",
                "content": f"Overall Alpha Score: {alpha.get('alpha_score', 0):+.1f}\n"
                          f"Signal: {alpha.get('signal', 'NEUTRAL')}\n"
                          f"Active Signals: {', '.join(alpha.get('active_signals', []))}",
                "type": "alpha",
                "data": alpha,
            })
        except Exception as e:
            sections.append({"title": "Alpha Score", "content": f"Unavailable: {e}", "type": "alpha"})

        try:
            from app.services.data.insider_trades import insider_trades_service
            insider = await insider_trades_service.get_insider_trades(ticker)
            sections.append({
                "title": "Insider Activity",
                "content": f"Recent filings: {len(insider)}\n"
                          f"Score: {insider_trades_service.score_insider_activity(insider):+.1f}",
                "type": "insider",
                "data": insider[:10],
            })
        except Exception as e:
            sections.append({"title": "Insider Activity", "content": f"Unavailable: {e}", "type": "insider"})

        try:
            from app.services.data.short_interest import short_interest_service
            short = await short_interest_service.get_short_interest(ticker)
            sections.append({
                "title": "Short Interest",
                "content": f"Short % Float: {short.get('short_pct_float', 'N/A')}\n"
                          f"Days to Cover: {short.get('days_to_cover', 'N/A')}",
                "type": "short_interest",
                "data": short,
            })
        except Exception as e:
            sections.append({"title": "Short Interest", "content": f"Unavailable: {e}", "type": "short_interest"})

        try:
            from app.services.data.retail_sentiment import retail_sentiment_service
            sentiment = await retail_sentiment_service.get_sentiment(ticker)
            sections.append({
                "title": "Retail Sentiment",
                "content": f"Bullish: {sentiment.get('bullish_pct', 0)}%\n"
                          f"Bearish: {sentiment.get('bearish_pct', 0)}%\n"
                          f"Mentions: {sentiment.get('total_mentions', 0)}",
                "type": "sentiment",
                "data": sentiment,
            })
        except Exception as e:
            sections.append({"title": "Retail Sentiment", "content": f"Unavailable: {e}", "type": "sentiment"})

        try:
            from app.services.data.technical_analysis import technical_analysis_service
            tech = await technical_analysis_service.get_indicators(ticker)
            sections.append({
                "title": "Technical Analysis",
                "content": f"Price: ${tech.get('price', 'N/A')}\n"
                          f"RSI: {tech.get('rsi', 'N/A')}\n"
                          f"Signals: {', '.join(tech.get('signals', []))}",
                "type": "technical",
                "data": tech,
            })
        except Exception as e:
            sections.append({"title": "Technical Analysis", "content": f"Unavailable: {e}", "type": "technical"})

        try:
            from app.services.data.financial_fundamentals import financial_fundamentals_service
            fund = await financial_fundamentals_service.get_fundamentals(ticker)
            sections.append({
                "title": "Fundamentals",
                "content": f"P/E: {fund.get('pe_ratio', 'N/A')}\n"
                          f"Revenue Growth: {fund.get('revenue_growth', 'N/A')}\n"
                          f"Profit Margin: {fund.get('profit_margin', 'N/A')}",
                "type": "fundamentals",
                "data": fund,
            })
        except Exception as e:
            sections.append({"title": "Fundamentals", "content": f"Unavailable: {e}", "type": "fundamentals"})

        result["sections"] = sections

        output_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")
        os.makedirs(output_dir, exist_ok=True)
        file_path = os.path.join(output_dir, f"dossier_{ticker}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
        result["file_path"] = file_path

        import json
        with open(file_path, "w") as f:
            json.dump(result, f, indent=2, default=str)

        return result


report_generator = ReportGenerator()
